//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Symlix.rc
//
#define IDS_PROJNAME                    100
#define IDD_ABOUTBOX                    100
#define IDR_SYMLIX                      101
#define IDR_SYMLIXERROR                 102
#define IDR_SYMLIXERRORRUN              103
#define IDR_SYMLIXEDITOR                104
#define IDD_SYMLIXHIDDENDLG             105
#define IDR_ARDATAPOST                  106
#define IDR_ARRUNPROGRESS               107
#define IDD_SYMRUNPROGRESSDLG           108
#define IDR_NUMCATRESOURCE              109
#define IDR_CNUMCATLOCALVALUES          110
#define IDR_NUMCATEXCELLOCALRES         111
#define IDR_CARDRM                      112
#define IDR_NUMCATDRM                   113
#define IDR_ARL_DRM                     114
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       201
#define IDC_STATIC_PROG                 201
#define IDC_LOGO                        202
#define IDR_POPUP1                      204
#define IDC_STATIC_TIME                 205
#define IDB_LOGO1                       206
#define IDB_BITMAPNUMCATON              207
#define IDB_BITMAPNUMCATOFF             208
#define IDB_BITMAPMASK1                 209
#define IDR_STATUS_STREAM               210
#define IDB_NUMCATTRADE                 210
#define IDR_STATUS_LINE                 211
#define IDR_TOOLBAR1                    211
#define IDB_BITMAPHELP1                 213
#define IDB_BITMAPHELP1MASK             214
#define IDB_BITMAPRUN1                  215
#define IDB_BITMAPRUNMASK1              216
#define IDB_BITMAPNUMCAT2007            217
#define IDB_BITMAPNUMCAT2007INACT       218
#define IDB_BITMAPNUMCATBUYNOW          219
#define IDB_BITMAPBUYNOWICON            220
#define ID_POPUP1_EVENTS_START          32768
#define ID_POPUP1_EVENTS_STOP           32769
#define ID_POPUP1_EVENTS_RECORD         32770
#define ID_POPUP1_EVENTS_DUMP           32771
#define ID_POPUP1_EQUATIONS_ORDINARY    32772
#define ID_POPUP1_EQUATIONS_SWITCHCASE  32773
#define ID_POPUP1_EQUATIONS_LOOKUP      32774
#define ID_POPUP1_FUNCTIONS_SIN         32776
#define ID_POPUP1_FUCNTIONS_COS         32777
#define ID_POPUP1_HELP                  32778
#define ID_POPUP1_SOLVER_RK4            32779
#define ID_POPUP1_SOLVER_RK4VS          32780
#define ID_POPUP1_SOLVER_RK4VSMT        32781
#define ID_POPUP1_SOLVER_RK5            32782
#define ID_POPUP1_SOLVER_RK5VS          32783
#define ID_POPUP1_EQUATIONS_DIFFERENTIAL 32784
#define ID_POPUP1_MACROS_INSERT         32785
#define ID_POPUP1_MACROS_LIMIT          32786
#define ID_POPUP1_MACROS_DEFINE         32786
#define ID_POPUP1_MACROS_TYPE           32787
#define ID_SAMPLES_TEMPLATES_SKELETON   32793
#define ID_HELP_EDITOR                  32803
#define ID_HELP_SYNTAX                  32804
#define ID_EXAMPLE_SIMPLE               32808
#define ID_POPUP1_FUNCTIONS_TAN         32809
#define ID_POPUP1_FUNCTIONS_COS         32810
#define ID_POPUP1_FUNCTIONS_ASIN        32816
#define ID_POPUP1_FUNCTIONS_ACOS        32817
#define ID_POPUP1_FUNCTIONS_ATAN        32818
#define ID_POPUP1_FUNCTIONS_LOG         32819
#define ID_POPUP1_FUNCTIONS_LN          32820
#define ID_POPUP1_FUNCTIONS_ABS         32821
#define ID_POPUP1_FUNCTIONS_EXP         32822
#define ID_POPUP1_SOLVER_RK3            32824
#define ID_POPUP1_SOLVER_RK3VS          32825
#define ID_POPUP1_ARRAYS_PLAINARRAY     32826
#define ID_POPUP1_ARRAYS_SHEET          32827
#define ID_POPUP1_INDEX_DEFINE          32828
#define ID_POPUP1_INDEX_EXPAND          32830
#define ID_POPUP1_SOLVER_SEQUENCESERIES 32832
#define ID_POPUP1_EVENTS_ITERATIONFROMTO 32833
#define ID_POPUP1_EVENTS_ITFROMTO       32833
#define ID_POPUP1_EVENTS_ITERATIONSERIES 32834
#define ID_POPUP1_EVENTS_DUMPEQUATIONS  32835
#define ID_RUN                          32838
#define ID_FILE_RUN                     32839
#define ID_POPUP1_ARRAYS_ARRAYFUNCTIONS_COUNT 32840
#define ID_POPUP1_ARRAYS_ARRAYFUNCTIONS_SUM 32841
#define ID_POPUP1_ARRAYS_ARRAYFUNCTIONS_AVRG 32842
#define ID_POPUP1_EVENTS_SYNC           32843
#define ID_POPUP1_EVENTS_PACE           32844
#define ID_POPUP1_EVENTS_REALTIME       32845
#define ID_POPUP1_FUNCTIONS_INT         32846
#define ID_POPUP1_FUNCTIONS_INTUP       32847
#define ID_POPUP1_SOLVERS_ONCE          32848
#define ID_POPUP1_EVENTS_CHANGEVALUE    32849
#define ATL_IDS_IDLEMESSAGE             0xE001
#define ID_FILE_NEW                     0xE100
#define ID_FILE_OPEN                    0xE101
#define ID_FILE_CLOSE                   0xE102
#define ID_FILE_SAVE                    0xE103
#define ID_FILE_SAVE_AS                 0xE104
#define ID_FILE_PAGE_SETUP              0xE105
#define ID_FILE_PRINT_SETUP             0xE106
#define ID_FILE_PRINT                   0xE107
#define ID_FILE_PRINT_PREVIEW           0xE109
#define ID_EDIT_CLEAR                   0xE120
#define ID_EDIT_CLEAR_ALL               0xE121
#define ID_EDIT_COPY                    0xE122
#define ID_EDIT_CUT                     0xE123
#define ID_EDIT_FIND                    0xE124
#define ID_EDIT_PASTE                   0xE125
#define ID_EDIT_REPEAT                  0xE128
#define ID_EDIT_REPLACE                 0xE129
#define ID_EDIT_SELECT_ALL              0xE12A
#define ID_EDIT_UNDO                    0xE12B
#define ID_EDIT_REDO                    0xE12C
#define ID_WINDOW_NEW                   0xE130
#define ID_WINDOW_ARRANGE               0xE131
#define ID_WINDOW_CASCADE               0xE132
#define ID_WINDOW_TILE_HORZ             0xE133
#define ID_WINDOW_TILE_VERT             0xE134
#define ID_WINDOW_SPLIT                 0xE135
#define ID_APP_ABOUT                    0xE140
#define ID_APP_EXIT                     0xE141
#define ID_NEXT_PANE                    0xE150
#define ID_PREV_PANE                    0xE151
#define ID_VIEW_TOOLBAR                 0xE800
#define ID_VIEW_STATUS_BAR              0xE801
#define ATL_IDS_SCSIZE                  0xEF00
#define ATL_IDS_SCMOVE                  0xEF01
#define ATL_IDS_SCMINIMIZE              0xEF02
#define ATL_IDS_SCMAXIMIZE              0xEF03
#define ATL_IDS_SCNEXTWINDOW            0xEF04
#define ATL_IDS_SCPREVWINDOW            0xEF05
#define ATL_IDS_SCCLOSE                 0xEF06
#define ATL_IDS_SCRESTORE               0xEF12
#define ATL_IDS_SCTASKLIST              0xEF13
#define ATL_IDS_MDICHILD                0xEF1F
#define ATL_IDS_MRU_FILE                0xEFDA
#define IDS_EDITOR_CANTOVRFORM          61403
#define IDS_VERSIONDESCRIPTION          61404
#define IDS_VERSIONDESCRIPTIONRES       61405
#define IDS_LORENZ_EXAMPLE              61406
#define IDS_LORENZ_EXAMPLE2             61407
#define IDS_LE_LOCAL_OPTIONS            61408
#define IDS_LE_KEY_USELOCALPREFIX       61409
#define IDS_LE_KEY_LOCALPREFIX          61410
#define IDS_LE_KEY_HIDELOCALMODELS      61411
#define IDS_LE_KEY_AUTOORGANISESHEETS   61412
#define IDS_LE_KEY_ORDERFORSHEETS       61413
#define IDS_LE_KEY_ORDEROFSHEETS        61414
#define IDS_LE_KEY_LASTRUNVERSION       61415
#define IDS_LE_KEY_EXTRADEBUG           61416
#define IDS_LE_TAG_LISTRESULTSSHEETS    61417
#define IDS_ORDER_SHEETS                61418
#define IDS_ORDER_CHARTS                61419
#define IDS_ORDER_MODELS                61420
#define IDS_ORDER_RESULTS               61421
#define IDS_NUMCATLOCRESDES             61422
#define ID_POPUP1_SOLVER_SEQFROMTO      61423

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        221
#define _APS_NEXT_COMMAND_VALUE         32850
#define _APS_NEXT_CONTROL_VALUE         206
#define _APS_NEXT_SYMED_VALUE           115
#endif
#endif
